local tstools_api = require("typescript-tools.api")

vim.keymap.set("n", "<leader>toi", function()
	tstools_api.organize_imports(true)
end, { desc = "[T]sTools [O]rganise [I]mports" })
vim.keymap.set("n", "<leader>tam", function()
	tstools_api.add_missing_imports(true)
end, { desc = "[T]sTools [A]dd [M]issing imports" })
vim.keymap.set("n", "<leader>trf", function()
	tstools_api.rename_file(false)
end, { desc = "[T]sTools [R]ename [F]ile" })
vim.keymap.set("n", "<leader>tru", function()
	tstools_api.remove_unused_imports(false)
end, { desc = "[T]sTools [R]emove [U]nused" })
vim.keymap.set("n", "<leader>tgs", function()
	tstools_api.go_to_source_definition(false)
end, { desc = "[T]sTools [G]o to [S]ource" })
